data_params:
  batch_size: 3000
  block_size: 100
  db_config: Datasets/PhysioNet_2012/data/mongo_config.yaml
  num_workers: 7
  sparsity: 0.3
  subset: 0.3
  test_length: 12877543
  train_length: 52091598
logging_params:
  name: AGG_v4
model_params:
  attention_drop: 0.2
  categorical_embedding_dim: 16
  categorical_input: 3
  dropout: 0.2
  feature_dim: 16
  input_dim: 1
  num_categories: -1
  num_heads: 8
  num_layers: 2
  num_node_types: 38
  num_spatial_components: 5
  query_includes_categorical: true
  spatial_embedding_dim: 16
  time_embedding_dim: 16
  type: Transformer
  type_embedding_dim: 16
optimiser_params:
  lr: 0.0001
  max_lr: 0.0002
  min_lr: 1.0e-05
  total_iters: 200
