data_params:
  batch_size: 12000
  block_size: 30
  db_config: ./Datasets/Localisation/data/mongo_config.yaml
  num_workers: 7
  sparsity: 0.1
  subset: 0.5
logging_params:
  name: AGG_v4
  scaler:
    fields:
    - X
    - Y
    - Z
    mean:
    - 2.8113479961092374
    - 1.6968769404813713
    - 0.4182104464547134
    std:
    - 0.91622372110056
    - 0.4737676249131146
    - 0.3791233780673026
    time: 6541081.600000001
    type: Normal
model_params:
  attention_drop: 0.2
  categorical_embedding_dim: 16
  dropout: 0.2
  feature_dim: 16
  input_dim: 3
  num_categories: 11
  num_heads: 8
  num_layers: 2
  num_node_types: 4
  num_spatial_components: 25
  query_includes_categorical: true
  spatial_embedding_dim: 16
  time_embedding_dim: 16
  type: Transformer
  type_embedding_dim: 16
optimiser_params:
  lr: 0.0001
  max_lr: 0.0002
  min_lr: 1.0e-05
  total_iters: 200
