data_params:
  block_size: 30
  sparsity: 0.7
  db_config: "./Datasets/Localisation/data/mongo_config.yaml"
  batch_size: 2000
  num_workers: 14
  subset: 0.3
  train_length: 3276564
  test_length: 820280
model_params:
  type: "Transformer"
  input_dim: 3
  feature_dim: 16
  num_heads: 8
  time_embedding_dim: 16
  type_embedding_dim: 16
  spatial_embedding_dim: 16
  categorical_embedding_dim: 16
  num_layers: 2
  attention_drop: 0.5
  dropout: 0.2
  query_includes_categorical: true
optimiser_params:
  lr: 0.0001
  max_lr: 0.0002
  min_lr: 0.00001
  total_iters: 200
logging_params:
  name: "AGG_v4"
