data_params:
  block_size: 1000
  sparsity: 0.1
  db_config: "Datasets/DoublePendulum/data/mongo_config.yaml"
  data_set: "sim_1M_@0.8_0.001_0.05_100_4.0"
  batch_size: 70
  num_workers: 7
  subset: 0.1
  dynamics_params:
    g: 9.81
    l_1: 1.0
    m_1: 1.5
    l_2: 1
    m_2: 1
    k_1: 0.05
  generation_params:
    theta_1_dot_distribution:
    - 0
    - 1.4770655749054404
    theta_2_dot_distribution:
    - 0.15390047391321904
    - 2.236036019867856
    train_length: 1000000
    test_length: 100000
    signal_std: 0.001
    sampling_rate: 0.05
    samples_per_simulation: 100
    prediction_limit: 0
model_params:
  type: "GraphAttentionNetwork"
  input_dim: 1
  feature_dim: 8
  num_heads: 4
  time_embedding_dim: 8
  type_embedding_dim: 8
  spatial_embedding_dim: 0
  categorical_embedding_dim: 0
  categorical_input: -1
  num_layers: 2
  attention_drop: 0.2
  dropout: 0.2
  query_includes_categorical: false
optimiser_params:
  lr: 0.0001
  max_lr: 0.0002
  min_lr: 0.0001
  total_iters: 200
logging_params:
  name: "AGG_v4"
