data_params:
  block_size: 10
  db_config: "./Datasets/Beijing/data/mongo_config.yaml"
  batch_size: 50
  num_workers: 12
  subset: 0.3
  train_length: 749529
  test_length: 373037
model_params:
  type: "Transformer"
  input_dim: 1
  feature_dim: 16
  num_heads: 8
  time_embedding_dim: 16
  type_embedding_dim: 16
  spatial_embedding_dim: 16
  categorical_embedding_dim: 16
  num_layers: 2
  dropout: 0.2
optimiser_params:
  lr: 0.001
  max_lr: 0.001
  min_lr: 0.0001
  total_iters: 100
logging_params:
  name: "AGG_v4"
