data_params:
  batch_size: 30
  classification: true
  db_config: Datasets/PhysioNet_2012/data/mongo_config.yaml
  freeze_pretrained: false
  num_workers: 7
  pretrained_path: lightning_logs/AGG-icu-13-08_22:34:10/checkpoints/model-epoch=18-val_RMSE_epoch=0.494384.ckpt
  sparsity: 0.1
  subset: 0.2
  test_split: 0.2
logging_params:
  name: AGG_classification
model_params:
  attention_drop: 0.5
  categorical_embedding_dim: 16
  categorical_input: 3
  dropout: 0.5
  feature_dim: 16
  input_dim: 1
  num_categories: -1
  num_heads: 8
  num_layers: 2
  num_node_types: 38
  num_spatial_components: 5
  query_includes_categorical: true
  query_includes_type: false
  spatial_embedding_dim: 16
  time_embedding_dim: 16
  transfer_learning: true
  type: Transformer
  type_embedding_dim: 16
optimiser_params:
  lr: 0.0001
  max_epochs: 20
  max_lr: 0.0002
  min_lr: 1.0e-05
  total_iters: 200
