data_params:
  batch_size: 50
  block_size: 10
  db_config: ./Datasets/Beijing/data/mongo_config.yaml
  num_workers: 12
  subset: 0.3
  test_length: 373037
  train_length: 749529
logging_params:
  name: AGG_v4
  scaler:
    fields:
    - PM2.5
    - PM10
    - SO2
    - NO2
    - CO
    - O3
    - TEMP
    - PRES
    - DEWP
    - RAIN
    - WSPM
    max:
    - 999.0
    - 999.0
    - 500.0
    - 290.0
    - 10000.0
    - 1071.0
    - 41.6
    - 1042.8
    - 29.1
    - 72.5
    - 13.2
    min:
    - 2.0
    - 2.0
    - 0.2856
    - 1.0265
    - 100.0
    - 0.2142
    - -19.9
    - 982.4
    - -43.4
    - 0.0
    - 0.0
    time: 36000
    type: MinMax
model_params:
  categorical_embedding_dim: 16
  dropout: 0.2
  feature_dim: 16
  input_dim: 1
  num_categories: 17
  num_heads: 8
  num_layers: 2
  num_node_types: 11
  num_spatial_components: 12
  spatial_embedding_dim: 16
  time_embedding_dim: 16
  type: Transformer
  type_embedding_dim: 16
optimiser_params:
  lr: 0.001
  max_lr: 0.001
  min_lr: 0.0001
  total_iters: 100
