data_params:
  batch_size: 30
  block_size: 1500
  block_steps: 150
  db_config: Datasets/Beijing/data/mongo_config.yaml
  num_workers: 7
  sparsity: 0.1
  subset: 0.5
logging_params:
  name: AGG_v4
model_params:
  attention_drop: 0.2
  categorical_embedding_dim: 16
  categorical_input: -1
  dropout: 0.2
  feature_dim: 16
  input_dim: 1
  num_categories: 17
  num_heads: 8
  num_layers: 2
  num_node_types: 11
  num_spatial_components: 12
  query_includes_categorical: true
  spatial_embedding_dim: 16
  time_embedding_dim: 16
  type: Transformer
  type_embedding_dim: 16
optimiser_params:
  lr: 0.0001
  max_lr: 0.0002
  min_lr: 0.0001
  total_iters: 200
